# version: '3.8' # Removed obsolete version tag

services:
  backend:
    build: ../backend
    ports:
      - "5000:5000"

  frontend:
    build: ../frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"

  # Test services are now correctly nested under 'services:'
  backend-test:
    build:
      context: ../backend
      dockerfile: Dockerfile.test
    volumes:
      - ../backend:/app
    environment:
      - PYTHONPATH=/app
    command: pytest -v --cov=. tests/

  frontend-test:
    build:
      context: ../frontend
      dockerfile: Dockerfile.test
    volumes:
      - ../frontend:/app
      - /app/node_modules # Be careful with this anonymous volume - it might hide local changes if not intended
    command: npm test